package betr.intern.spring_users.model;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "users")
public class User {

        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY) //autogenerated value for the primary keys in the table

        private Long id;
        private String name;
        private String email;
        //empty constructor for JPA
        public User() {}

        public User(String email, String name){
            this.email=email;
            this.name=name;
        }

        private Long getId(){
            return this.id;
        }

        public String getName(){
            return this.name;
        }

        private void setId(Long id){
            this.id=id;
        }

        public void setName(String name){
            this.name=name;
        }

        public String getEmail(){
            return this.email;
        }

        private void setName(){
            this.email=email;
        }

    public void setEmail(String email) {
            this.email=email;
    }
}
